# SITE CONFIGURATION
baseurl: ""
url: "https://Mahadev10.github.io"

# THEME-SPECIFIC CONFIGURATION
title: "Maha[Dev]"                                  # site's title
description: "👋Hello, my name is Mahadev Reddy and I am a self-taught programmer. This site is host to a variety of things professional and personal; you can learn more about who I am or read my articles related to programming."      # used by search engines
avatar: assets/img/programmer.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab
author: "Kasireddy Mahadev Reddy"
# Header and footer text
header_text: <code>Learn</code> and <code>Code</code>  # Change Blog header text
header_feature_image: assets/img/pexels/computer.jpeg
footer_text: "Mahadev Reddy©️ 2022"
# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.
# Defaults
defaults:
  - 
    scope:
      path: "" 
      type: "posts"
    values:
      permalink: /:title.html
      layout: "post"
      author: "Mahadev Reddy"  
      comments: true
# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname: "mahadev10"                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap    

# If using as a remote_theme in github

# Sitemap
