# SITE CONFIGURATION
baseurl: ""
url: "https://Mahadev10.github.io"

# THEME-SPECIFIC CONFIGURATION
title: "Maha[Dev]"                                  # site's title
description: "👋Hello, my name is Mahadev Reddy and I am a self-taught programmer. This site is host to a variety of things professional and personal; you can learn more about who I am or read my articles related to programming."      # used by search engines
avatar: assets/img/programmer.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab
author: "Kasireddy Mahadev Reddy"
# Header and footer text
header_text: <code>Learn</code> and <code>Code</code>  # Change Blog header text
header_feature_image: assets/img/pexels/computer.jpeg
footer_text: "Mahadev Reddy©️ 2022"
# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.
# Defaults
defaults:
  - 
    scope:
      path: "" 
      type: "posts"
    values:
      permalink: /:title.html
      layout: "post"
      author: "Mahadev"  
      comments: true
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      icons:
         html: <i class="devicon-html5-plain-wordmark colored" style="font-size:30px;margin-right:5px;"></i>
         css: <i class="devicon-css3-plain-wordmark colored" style="font-size:30px;margin-right:5px;"></i>
         js: <i class="devicon-javascript-plain colored" style="font-size:30px;margin-right:5px;"></i>
         jquery: <i class="devicon-jquery-plain-wordmark colored" style="font-size:30px;margin-right:5px;"></i>
         react: <i class="devicon-react-original-wordmark colored" style="font-size:30px;margin-right:5px;"></i>
         redux: <i class="devicon-redux-original colored" style="font-size:30px;margin-right:5px;"></i>
         saas: <i class="devicon-sass-original colored" style="font-size:30px;margin-right:5px;"></i>
         sc: <img style="padding:0;margin-right:5px;vertical-align:baseline" src="https://camo.githubusercontent.com/5e6b5d9da90f61f872931b769d9bf65254c2fcfda569a972b9be45b4a921f8a3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7374796c652d2546302539462539322538352532307374796c65642d2d636f6d706f6e656e74732d6f72616e67652e7376673f636f6c6f72423d64616133353726636f6c6f72413d646237343865" />
         tailwind: <i class="devicon-tailwindcss-plain colored" style="font-size:30px;margin-right:5px;"></i>
         python: <i class="devicon-python-plain-wordmark colored" style="color:blue;font-size:30px;margin-right:5px;"></i>
         django: <i class="devicon-django-plain-wordmark colored" style="font-size:30px;margin-right:5px;"></i>

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# Comments
comments:
  disqus_shortname: "mahadev10"                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap    

# If using as a remote_theme in github

# Sitemap
